#!/usr/bin/env python3

import requests
import xmltodict
import itertools
import re


urls = [
  "https://dblp.org/pers/f/Fiume:Eugene.xml",
  "https://dblp.uni-trier.de/pers/b/Baecker:Ronald.xml",
  "https://dblp.uni-trier.de/pers/xx/j/Jacobson:Alec.xml",
  "https://dblp.org/pers/xx/g/Grinspun:Eitan.xml",
  "https://dblp.org/pers/xx/l/Levin:David_I=_W=.xml",
  "https://dblp.org/pers/xx/w/Wigdor:Daniel_J=.xml",
  "https://dblp.org/pers/k/Kutulakos:Kiriakos_N=.xml",
  "https://dblp.uni-trier.de/pers/xx/t/Truong:Khai_N=.xml",
  "https://dblp.org/pers/xx/a/Ahmed:Syed_Ishtiaque.xml",
  "https://dblp.uni-trier.de/pers/c/Chevalier:Fanny.xml",
  "https://dblp.org/pers/xx/b/Balakrishnan:Ravin.xml",
  "https://dblp.org/pers/w/Williams:Joseph_Jay.xml",
  "https://dblp.org/pers/g/Grossman:Tovi.xml",
  "https://dblp.uni-trier.de/pers/m/Munteanu:Cosmin.xml"
  ]

everyone = list(map(lambda url: xmltodict.parse(requests.get(url).content),urls))

allpubs = list(itertools.chain(*[entry["dblpperson"]["r"] for entry in everyone]))

## Helper to dump out list of all publications
#allpubs =  \
#  list(map(lambda pub: pub["article"], list(filter(lambda pub : 
#      "article" in pub and pub["article"]["journal"] , allpubs)) )) +  \
#  list(map(lambda pub: pub["inproceedings"], list(filter(lambda pub : 
#      "inproceedings" in pub and pub["inproceedings"]["booktitle"] , allpubs)) ))
#print("allvenues = [")
#print(*sorted(list(set(map(lambda pub : pub["journal"] if "journal" in pub else pub["booktitle"],allpubs)))),sep=',\n')
#print("  ]")

allvenues = [
  "3DIM",
  "3DUI",
  "AAAI",
  "ACCV (4)",
  "ACL",
  "ACL/IJCNLP",
  "ACM DEV",
  "ACM DEV (3)",
  "ACM DEV (4)",
  "ACM Multimedia",
  "ACM Multimedia (2)",
  "ACM Queue",
  "ACM Symposium on Document Engineering",
  "ACM Symposium on User Interface Software and Technology",
  "ACM Trans. Comput.-Hum. Interact.",
  "ACM Trans. Graph.",
  "ACM Trans. Inf. Syst.",
  "AFIPS Spring Joint Computing Conference",
  "AI Magazine",
  "AIED",
  "AIED (2)",
  "AIED Workshops",
  "AINA Workshops",
  "ASONAM",
  "ASSETS",
  "AVI",
  "Advances in Computer Graphics",
  "Afrigraph",
  "Artif. Intell.",
  "BCS HCI",
  "BooksOnline",
  "CASCON",
  "CBMI",
  "CCS",
  "CHI",
  "CHI Conference Companion",
  "CHI Extended Abstracts",
  "COMPASS",
  "CSCW",
  "CSCW Companion",
  "CSCWD",
  "CUI",
  "CVGIP: Graphical Model and Image Processing",
  "CVPR",
  "CVPR (1)",
  "CoRR",
  "CogSci",
  "Cognitive Science",
  "Commun. ACM",
  "CompEd",
  "Comput. Graph. Forum",
  "Computer Aided Geometric Design",
  "Computer Vision, Graphics, and Image Processing",
  "Computers & Chemistry",
  "Computers & Graphics",
  "Computers and Their Applications",
  "Computers in Human Behavior",
  "Conference on Designing Interactive Systems",
  "Conference on Designing Interactive Systems (Companion Volume)",
  "Creativity & Cognition",
  "DBSocial",
  "EAI Endorsed Trans. Pervasive Health Technol.",
  "EC-TEL",
  "ECCV (1)",
  "ECCV (3)",
  "ECCV (4)",
  "ECSCW",
  "EDM",
  "EGC",
  "EICS",
  "Eurographics (STARs)",
  "Eurographics (Short Papers)",
  "EvalMetrics@NAACL-HLT",
  "Expressive",
  "Foundations and Trends in Computer Graphics and Vision",
  "Foundations and Trends in Human-Computer Interaction",
  "Future Play",
  "GISTAM",
  "GRAPHITE",
  "GetMobile",
  "Graphical Models",
  "Graphics Interface",
  "Graphs and Combinatorics",
  "HCI (15)",
  "HCI (2)",
  "HCI (26)",
  "HCI (9)",
  "HCITOCH",
  "HCOMP@AAAI",
  "HLT-NAACL",
  "Human Motion",
  "Human-Computer Interaction",
  "Hypertext",
  "I. J. Artificial Intelligence in Education",
  "I. J. Medical Informatics",
  "I. J. Robotics Res.",
  "ICALT",
  "ICASSP",
  "ICAT-EGVE",
  "ICCP",
  "ICCS",
  "ICCV",
  "ICER",
  "ICLR (Poster)",
  "ICLS",
  "ICMC",
  "ICMI",
  "ICRA",
  "ICRA (1)",
  "ICSE",
  "ICTD",
  "IEEE Computer",
  "IEEE Computer Graphics and Applications",
  "IEEE Pervasive Computing",
  "IEEE Software",
  "IEEE Trans. Automation Science and Engineering",
  "IEEE Trans. Pattern Anal. Mach. Intell.",
  "IEEE Trans. Vis. Comput. Graph.",
  "IEEE VAST",
  "IEEE Visualization",
  "IHM",
  "IJCAI",
  "IJMHCI",
  "IMWUT",
  "INFOVIS",
  "INTERACT",
  "INTERACT (1)",
  "INTERACT (2)",
  "INTERACT (4)",
  "INTERCHI",
  "INTERSPEECH",
  "IPDPS",
  "IROS",
  "ISM",
  "ISMAR",
  "ISS",
  "ISSCC",
  "ISVD",
  "ISWC",
  "ITS",
  "ITiCSE",
  "IUI",
  "IUI Companion",
  "IWPSE",
  "Inf. Process. Lett.",
  "Inf. Process. Manage.",
  "Int. J. Hum.-Comput. Stud.",
  "Interact. Techn. Smart Edu.",
  "Interactions",
  "International Journal of Computer Vision",
  "J. Comput. Physics",
  "J. Graphics Tools",
  "J. Solid-State Circuits",
  "J. Vis. Lang. Comput.",
  "JCDL",
  "JCP",
  "L@S",
  "LAK",
  "LIMITS",
  "LREC",
  "MVA",
  "Medical Image Analysis",
  "MobiSys",
  "Mobile HCI",
  "Mobile HCI (Companion)",
  "MobileHCI",
  "MobileHCI Adjunct",
  "Multimedia Information Retrieval",
  "Multiscale Modeling & Simulation",
  "NIPS",
  "NeurIPS",
  "NordiCHI",
  "Object Representation in Computer Vision",
  "PACMCGIT",
  "PACMHCI",
  "PDC",
  "Pacific Conference on Computer Graphics and Applications",
  "PacificVis",
  "Pattern Recognition Letters",
  "Personal and Ubiquitous Computing",
  "Pervasive",
  "Pervasive and Mobile Computing",
  "PervasiveHealth",
  "RecSys",
  "RecSys Posters",
  "Rendering Techniques",
  "SAC",
  "SBM",
  "SI3D",
  "SIGCSE",
  "SIGDOC",
  "SIGGRAPH",
  "SIGGRAPH ASIA (Courses)",
  "SIGGRAPH ASIA Courses",
  "SIGGRAPH Abstracts and Applications",
  "SIGGRAPH Award Recipients",
  "SIGGRAPH Courses",
  "SIGGRAPH Emerging Technologies",
  "SIGGRAPH Posters",
  "SIGGRAPH Sketches",
  "SIGGRAPH Studio",
  "SIGGRAPH Talks",
  "SLT",
  "SOUPS",
  "Shape Modeling International",
  "Sig. Proc.: Image Comm.",
  "Symposium on Computer Animation",
  "Symposium on Geometry Processing",
  "TACCESS",
  "Tabletop",
  "Tangible and Embedded Interaction",
  "UAI",
  "UIST",
  "UIST (Adjunct Volume)",
  "UMAP (Adjunct Publication)",
  "UMAP Workshops",
  "UbiComp",
  "Universal Access in the Information Society",
  "VIS",
  "VL/HCC",
  "VMV",
  "VRAIS",
  "WALCOM",
  "WWW",
  "WebMedia",
  "WebNet",
  "eLearn Magazine"
  ]

# Might be more scalable to maintain a blacklist (all publications are default
# included), depends if we want to be conservative or liberal w.r.t. "new"
# venues (new might be legit new or might be new name on dblp)
whitelist = [
  "3DIM",
  "3DUI",
  "AAAI",
  "ACCV (4)",
  "ACL",
  "ACL/IJCNLP",
  "ACM DEV",
  "ACM DEV (3)",
  "ACM DEV (4)",
  "ACM Multimedia",
  "ACM Multimedia (2)",
  "ACM Queue",
  "ACM Symposium on Document Engineering",
  "ACM Symposium on User Interface Software and Technology",
  "ACM Trans. Comput.-Hum. Interact.",
  "ACM Trans. Graph.",
  "ACM Trans. Inf. Syst.",
  "AFIPS Spring Joint Computing Conference",
  "AI Magazine",
  "AIED",
  "AIED (2)",
  "AIED Workshops",
  "AINA Workshops",
  "ASONAM",
  "ASSETS",
  "AVI",
  "Advances in Computer Graphics",
  "Afrigraph",
  "Artif. Intell.",
  "BCS HCI",
  "CASCON",
  "CBMI",
  "CCS",
  "CHI",
  "COMPASS",
  "CSCW",
  "CSCWD",
  "CUI",
  "CVGIP: Graphical Model and Image Processing",
  "CVPR",
  "CVPR (1)",
  "CogSci",
  "Cognitive Science",
  "Commun. ACM",
  "CompEd",
  "Comput. Graph. Forum",
  "Computer Aided Geometric Design",
  "Computer Vision, Graphics, and Image Processing",
  "Computers & Chemistry",
  "Computers & Graphics",
  "Computers and Their Applications",
  "Computers in Human Behavior",
  "Conference on Designing Interactive Systems",
  "Creativity & Cognition",
  "DBSocial",
  "EAI Endorsed Trans. Pervasive Health Technol.",
  "EC-TEL",
  "ECCV (1)",
  "ECCV (3)",
  "ECCV (4)",
  "ECSCW",
  "EDM",
  "EGC",
  "EICS",
  "Eurographics (STARs)",
  "EvalMetrics@NAACL-HLT",
  "Expressive",
  "Foundations and Trends in Computer Graphics and Vision",
  "Foundations and Trends in Human-Computer Interaction",
  "Future Play",
  "GISTAM",
  "GRAPHITE",
  "GetMobile",
  "Graphical Models",
  "Graphics Interface",
  "Graphs and Combinatorics",
  "HCI (15)",
  "HCI (2)",
  "HCI (26)",
  "HCI (9)",
  "HCITOCH",
  "HCOMP@AAAI",
  "HLT-NAACL",
  "Human Motion",
  "Human-Computer Interaction",
  "Hypertext",
  "I. J. Artificial Intelligence in Education",
  "I. J. Medical Informatics",
  "I. J. Robotics Res.",
  "ICALT",
  "ICASSP",
  "ICAT-EGVE",
  "ICCP",
  "ICCS",
  "ICCV",
  "ICER",
  "ICLR (Poster)",
  "ICLS",
  "ICMC",
  "ICMI",
  "ICRA",
  "ICRA (1)",
  "ICSE",
  "ICTD",
  "IEEE Computer",
  "IEEE Computer Graphics and Applications",
  "IEEE Pervasive Computing",
  "IEEE Software",
  "IEEE Trans. Automation Science and Engineering",
  "IEEE Trans. Pattern Anal. Mach. Intell.",
  "IEEE Trans. Vis. Comput. Graph.",
  "IEEE VAST",
  "IEEE Visualization",
  "IHM",
  "IJCAI",
  "IJMHCI",
  "IMWUT",
  "INFOVIS",
  "INTERACT",
  "INTERACT (1)",
  "INTERACT (2)",
  "INTERACT (4)",
  "INTERCHI",
  "INTERSPEECH",
  "IPDPS",
  "IROS",
  "ISM",
  "ISMAR",
  "ISS",
  "ISSCC",
  "ISVD",
  "ISWC",
  "ITS",
  "ITiCSE",
  "IUI",
  "IUI Companion",
  "IWPSE",
  "Inf. Process. Lett.",
  "Inf. Process. Manage.",
  "Int. J. Hum.-Comput. Stud.",
  "Interact. Techn. Smart Edu.",
  "International Journal of Computer Vision",
  "J. Comput. Physics",
  "J. Graphics Tools",
  "J. Solid-State Circuits",
  "J. Vis. Lang. Comput.",
  "JCDL",
  "JCP",
  "L@S",
  "LAK",
  "LIMITS",
  "LREC",
  "MVA",
  "Medical Image Analysis",
  "MobiSys",
  "Mobile HCI",
  "MobileHCI",
  "MobileHCI Adjunct",
  "Multimedia Information Retrieval",
  "Multiscale Modeling & Simulation",
  "NIPS",
  "NeurIPS",
  "NordiCHI",
  "Object Representation in Computer Vision",
  "PACMCGIT",
  "PACMHCI",
  "PDC",
  "Pacific Conference on Computer Graphics and Applications",
  "PacificVis",
  "Pattern Recognition Letters",
  "Personal and Ubiquitous Computing",
  "Pervasive",
  "Pervasive and Mobile Computing",
  "PervasiveHealth",
  "RecSys",
  "RecSys Posters",
  "Rendering Techniques",
  "SAC",
  "SBM",
  "SI3D",
  "SIGCSE",
  "SIGDOC",
  "SIGGRAPH",
  "SLT",
  "SOUPS",
  "Shape Modeling International",
  "Sig. Proc.: Image Comm.",
  "Symposium on Computer Animation",
  "Symposium on Geometry Processing",
  "TACCESS",
  "Tabletop",
  "Tangible and Embedded Interaction",
  "UAI",
  "UIST",
  "UMAP Workshops",
  "UbiComp",
  "Universal Access in the Information Society",
  "VIS",
  "VL/HCC",
  "VMV",
  "VRAIS",
  "WALCOM",
  "WWW",
  "WebMedia",
  "WebNet",
  "eLearn Magazine"
  ]

allpubs =  \
  list(map(lambda pub: pub["article"], list(filter(lambda pub : 
      "article" in pub and pub["article"]["journal"] in whitelist, allpubs)) )) +  \
  list(map(lambda pub: pub["inproceedings"], list(filter(lambda pub : 
      "inproceedings" in pub and pub["inproceedings"]["booktitle"] in whitelist, allpubs)) ))


allpubs = sorted(allpubs,key=lambda pub : pub["year"]+pub["@mdate"],reverse=True)

print("<!DOCTYPE HTML>")
print('''
<html>
  <head>
    <link rel="stylesheet" href=style.css><meta charset="utf-8"/>
  </head>
<body>
  <h1>dgp Publications</h1>
  <ol reversed>''')
lis = []
for pub in allpubs:
  venue = pub["journal"] if "journal" in pub else pub["booktitle"]
  if isinstance(pub["author"],list):
    authors = ", ".join([re.sub(r' [0-9]*$',"",author["#text"]) for author in pub["author"]])
  else:
    authors = pub["author"]["#text"]
  if "ee" in pub:
    if isinstance(pub["ee"],str):
      url = pub["ee"] 
    elif isinstance(pub["ee"],list):
      url = pub["ee"][0]
    else:
      url = pub["ee"]["#text"] 
  else:
    url = "#"
  if isinstance(pub["title"],str):
    title = pub["title"]
  else:
    title = pub["title"]["i"]+pub["title"]["#text"]

  lis.append((pub["year"],("<li><a class=pubtitle href=\"%s\">%s</a><br><span class=authors>%s</span><br><span class=venue>%s</span>, %s.</li>" % (url,title,authors,venue,pub["year"]))))

lis = [entry[1] for entry in sorted(set(lis),reverse=True)]
print("\n".join(lis))
print("</ol></body></html>")

#person = doc['dblpperson']
## all publications by this person
#for entry in person['r']:
#    if "article" in entry:
#        article = entry['article']
#    elif "inproceedings" in entry:
#        article = entry['inproceedings']
#    else:
#        continue
#    print(article['year'])
#
#
#
#
